export default {
  avatar_Icon: require('@/src/assets/png/avatar.png'),
  ceo_Icon: require('@/src/assets/png/ceo.png'),
  location_active_Icon: require('@/src/assets/svg/location_on.svg'),
  email_Icon: require('@/src/assets/png/email.png'),
  empool_waters_Icon: require('@/src/assets/png/logo__1_-removebg-preview.png'),
  dg_waters_Icon: require('@/src/assets/png/dg-water-firma-logo-h-normal.png'),
  darkLogo_Icon: require('@/src/assets/png/logo_dark.png'),
  whiteLogo_png: require('@/src/assets/png/logo_light.png'),
  twitter_Icon: require('@/src/assets/png/Twitter.png'),
  youtube_Icon: require('@/src/assets/png/Youtube.png'),
  apple_Icon: require('@/src/assets/svg/socials/apple.svg'),
  faceBook_Icon: require('@/src/assets/svg/socials/facebook.svg'),
  instagram_Icon: require('@/src/assets/svg/socials/instagram.svg'),
  x_Icon: require('@/src/assets/svg/socials/x.svg'),
  linkedIn_Icon: require('@/src/assets/svg/socials/linkedin.svg'),
  google_Icon: require('@/src/assets/svg/socials/google.svg'),
  filter_Icon: require('@/src/assets/svg/filter.svg'),
  edit_Icon: require('@/src/assets/svg/edit.svg'),
  phone_active_Icon: require('@/src/assets/svg/phone_active.svg'),
  email_active_Icon: require('@/src/assets/svg/email_active.svg'),
  ai_automation_Icon: require('@/src/assets/png/ai-automation.png'),
  data_analysis_Icon: require('@/src/assets/png/data-analysis.png'),
  media_marketing_Icon: require('@/src/assets/png/media-marketing.png'),
};
